### PR TITLE
feat(close-up): add option close blinds upward (versus default dowward)

### PR DESCRIPTION
**Pull request by apexad**
@gregmichael. I have not had a chance to test this quite yet as my blinds are not currently hung, but I am hoping this should be correct.  Should be able to test within the next few days.

### CODE REVIEW

**Comment by gregmichael** [comment]
@apexad Testing underway, will update shortly!

**Comment by gregmichael** [comment]
Main function (reversal) - Working nicely! 

Issue: Homebridge is reporting that Blinds status is "open" when in it is closed state, and vice versa.

**Comment by apexad** [comment]
ok, try it now.  hopefully reporting should be corrected.

**Comment by apexad** [comment]
Never mind. There will still be issues. Will look at this again in the morning.

**Comment by apexad** [comment]
Alright, this is ready to be tested again!

**Comment by gregmichael** [comment]
Testing!

**Comment by apexad** [comment]
Hmm, looks like I will have to get my own blinds up and running again. Will do this later today.

**Comment by apexad** [comment]
yep I know, this is some weird math as 200 has to be 0 and 100 has to be 100, trying to figure that out. ignore my commits for now.  Once I am confident this is good, I will squash them all and let you know to test again before I merge this.

**Comment by apexad** [comment]
Alright, hoping this should finally be good now!  Go ahead and try testing again

**Comment by gregmichael** [comment]
Ok so maybe it's me... Is there a way to flush homebridge? I am still seeing the same results.

**Comment by apexad** [comment]
Be sure to restart homebridge after reinstalling the plugin

**Comment by gregmichael** [comment]
Restarted, flushed - updated and restarted etc. 

1. status is correct for non-closeup
2. status is incorrect for closeup option

**Comment by apexad** [comment]
Hmmm. So just make sure the blinds are open when you change it to close up and restart homebridge.

**Comment by gregmichael** [comment]
Hmm... Still reporting opposite after following steps above.

Blinds report open when initially brought online but selecting them to close didn't do anything to blind, but did change status to close (they stayed open). When then selecting to open they then physically closed.

**Comment by apexad** [comment]
Just want to make sure you are running npm install again for this branch, right?

**Comment by gregmichael** [comment]
sudo npm install git://github.com/apexad/homebridge-mysmartblinds-bridge#closeUp

Gregory Michael
(310) 279-2352
gregorymichael.com

CONFIDENTIALITY NOTICE:    This email, including any attachments, contains information from Gregory Michael, which may be confidential or privileged. The information is intended to be for the use of the individual or entity named above. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited. If you have received this email in error, please notify the sender immediately by "reply to sender only" message and destroy all electronic and hard copies of the communication, including attachments.

**Comment by apexad** [comment]
Yes, that is correct, so re-ran it? and it is still not working as expected?

**Comment by gregmichael** [comment]
Yes that's correct

Gregory Michael
(310) 279-2352
gregorymichael.com

CONFIDENTIALITY NOTICE:    This email, including any attachments, contains information from Gregory Michael, which may be confidential or privileged. The information is intended to be for the use of the individual or entity named above. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited. If you have received this email in error, please notify the sender immediately by "reply to sender only" message and destroy all electronic and hard copies of the communication, including attachments.

**Comment by apexad** [comment]
FYI, be careful about replying to GitHub emails. It is putting your entire signature into the thread list. @gregmichael

I will have to hold off on this until Wednesday night or so to do some further testing on my end. Will let you know.

**Comment by apexad** [comment]
I edited out your signature on the emails you sent.

**Comment by apexad** [comment]
@gregmichael Got my blind set back up today and this is working as expected.  Not sure if it is an install issue or something weird on your end.  Either way, I will merge this as version 1.3.0 sometime tonight.  Once this is done I recommend downloading this version from npmjs.com and installing it

If you still have issues please make an issue on GitHub.

**Pull request merged**
